# Generated by Django 4.1.6 on 2023-02-12 17:04

from django.db import migrations, models
import django.db.models.deletion
import rest_api_lecture.web_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('salary', models.PositiveIntegerField(validators=[rest_api_lecture.web_api.models.validate_min_salary])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web_api.department')),
            ],
        ),
    ]
